name: Test The Docker Build
on: [pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Ruby-Network'
    steps:
      - name: Checkout
        uses: actions/checkout@v3      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf
      - name: Build 
        uses: docker/build-push-action@ad44023a93711e2821f8e83c0e57c4ddd9b934e0
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ruby-network/ruby-network:testing
